### ISSUE TITLE
C++ generator fails on recursive definitions without parameters

### ISSUE THREAD

**Issue by fklebert** [welovemaps/zserio#8]
Parser and JAVA generators are fine using the following schema, but C++ emitter throws errors.

Schema:
```
package tutorial;


struct Employee
{
  uint8           age : age <= 65; // max age is 65
  string          name;
  uint16          salary;
  optional uint16 bonus;
  Title           title;
 
  // if employee is a team lead, list the team members
  Employee      teamMember[] if title == Title.TEAM_LEAD;
};
 
enum uint8 Title
{
  DEVELOPER = 0,
  TEAM_LEAD = 1,
  CTO       = 2
};
```
Error generated by C++ generator:

```
Emitting C++ code
[ERROR] Internal error
java.lang.StackOverflowError
        at java.util.ArrayList$Itr.<init>(Unknown Source)
        at java.util.ArrayList.iterator(Unknown Source)
        at zserio.ast.CompoundType.needsChildrenInitialization(CompoundType.java:184)
```

**Comment by Mi-La** [comment]
Also check why the core doesn't handle the exception from C++ generator.

**Comment by mikir** [comment]
We should implement test examples for recursion as well.

**Comment by mikir** [comment]
Tests for recursion have been implemented in https://github.com/welovemaps/zserio/commit/57beddd3ae46a556c278cafdf75648511447e875.
